_target_: radium.models.cifar10_module.CIFAR10LitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: radium.models.components.simple_dense_net.SimpleDenseNet
  input_size: 3072
  lin1_size: 64
  lin2_size: 64
  lin3_size: 64
  output_size: 10